server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /posts/index.json {
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location /posts/ {
        try_files $uri =404;
    }
    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
